version: '3.9'

services:
  nginx:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - auth-server
      - kms
      - db

  backend:
    build: ./backend
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/app
      - SPRING_DATASOURCE_USERNAME=appuser
      - SPRING_DATASOURCE_PASSWORD=apppassword

  auth-server:
    build: ./auth
    expose:
      - "8081"
    environment:
      - AUTH_DB_URL=jdbc:postgresql://db:5432/app

  kms:
    build: ./kms
    expose:
      - "8000"
    environment:
      - DB_URL=postgresql://db:5432/app

  db:
    image: postgres:15
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword

volumes:
  db-data:
