version: '3.9'

services:
  backend:
    ports:
      - "8080:8080"
  dek:
    ports:
      - "8082:8082"

  auth-server:
    entrypoint: []
    command: "./mvnw spring-boot:run -Dspring-boot.run.arguments=--logging.level.org.springframework.security=DEBUG"
    ports:
      - "8081:8081"
    working_dir: /app
    volumes:
      - ./auth:/app
      - ~/.m2:/root/.m2
    environment:
      - SPRING_PROFILES_ACTIVE=dev
