version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    working_dir: /app
    command: npm run dev -- --host
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost

  backend:
    entrypoint: []
    command: "./mvnw spring-boot:run -Dspring-boot.run.arguments=--logging.level.org.springframework.security=DEBUG"
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  auth-server:
    entrypoint: []
    command: "./mvnw spring-boot:run -Dspring-boot.run.arguments=--logging.level.org.springframework.security=DEBUG"
    ports:
      - "8081:8081"
    working_dir: /app
    volumes:
      - ./auth:/app
      - ~/.m2:/root/.m2
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  kms:
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./kms:/app
    working_dir: /app
    ports:
      - "8000:8000"       # 這行是新增的，讓宿主機可以連到容器的 8000 端口
